const { Web3 } = require('web3');
const fs = require('fs');

// Correct connection to local Ganache (verify Ganache's port)
const web3 = new Web3('http://127.0.0.1:7545');

// Correctly load ABI and Bytecode generated by the compile.js file
const abi = JSON.parse(fs.readFileSync('MyTokenAbi.json', 'utf8'));
const bytecode = fs.readFileSync('MyTokenBytecode.bin', 'utf8');

async function deployContract() {
    const accounts = await web3.eth.getAccounts();

    console.log('Deploying from account:', accounts[0]);

    const contract = new web3.eth.Contract(abi);

    const initialSupply = web3.utils.toWei('1000', 'ether');

    const deployedContract = await contract
        .deploy({ data: '0x' + bytecode, arguments: [initialSupply] })
        .send({ from: accounts[0], gas: 4000000 });

    console.log('Contract deployed at address:', deployedContract.options.address);
}

deployContract().catch(console.error);
